# Check the documentation at https://goreleaser.com

# Adapted from https://github.com/LGUG2Z/komorebi/blob/e240bc770619fa7c1f311b8a376551f2dde8a2d7/.goreleaser.yml
version: 2
project_name: clavy

before:
  hooks:
    - bash -c 'echo "package main; func main() { panic(0xdeadbeef) }" > dummy.go'

builds:
  - id: clavy
    binary: clavy
    main: dummy.go
    # env:
    #   - CGO_ENABLED=0
    goos:
      - darwin
    goarch:
      - amd64
      - arm64
    hooks:
      # Actually override the release binary.
      post: bash -c 'mv -f target/gh-artifacts/{{ .Name }}_{{ .Os }}_{{ .Arch }}/{{ .Name }} {{ .Path }}'

universal_binaries:
  - replace: true
    id: clavy
    hooks:
      post: codesign -dvvv --force --sign - {{ .Path }}

archives:
  - format: tar.gz
    # https://goreleaser.com/customization/archive/#packaging-only-the-binaries
    files:
      - none*
    name_template: >-
      {{ .ProjectName }}_
      {{- .Os }}_
      {{- if eq .Arch "all" }}universal2
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
      {{- if .Arm }}v{{ .Arm }}{{ end }}
    format_overrides:
      # Use zip for windows archives
      - goos: windows
        format: zip

checksum:
  name_template: "checksums.txt"

release:
  prerelease: auto

brews:
  # https://goreleaser.com/customization/homebrew/
  - homepage: https://github.com/rami3l/clavy
    description: An input source switching daemon for macOS.
    license: GPL-3.0-only

    custom_block: |
      head "https://github.com/rami3l/clavy.git"

      head do
        depends_on "rust" => :build
      end

    install: |
      if build.head? then
        system "cargo", "install", *std_cargo_args
      else
        bin.install "clavy"
      end

    test: |
      system "#{bin}/clavy --help"

    # TODO: Use `auto` when we move out of prerelease.
    # skip_upload: auto
    skip_upload: false

    # https://github.com/goreleaser/goreleaser/blob/a0f0d01a8143913cde72ebc1248abef089ae9b27/.goreleaser.yaml#L211
    repository:
      owner: rami3l
      name: homebrew-tap
      branch: "{{.ProjectName}}-{{.Version}}"
      token: "{{ .Env.TAP_GITHUB_TOKEN }}"
      pull_request:
        enabled: true
        base:
          owner: rami3l
          name: homebrew-tap
          branch: master
